tap "atlassian/acli"
tap "caskformula/caskformula"
tap "databricks/tap"
tap "hashicorp/tap"
tap "jakehilborn/jakehilborn"
tap "FelixKratz/formulae"
tap "lawzava/scrape", "https://github.com/lawzava/scrape"
tap "mrkai77/cask"
tap "ngrok/ngrok"
tap "nikitabobko/tap"
tap "petere/postgresql"
tap "shopify/shopify"
brew "openssl@3"
brew "libssh"
brew "ansible"
brew "jpeg-xl"
brew "aom"
brew "apr-util"
brew "atuin"
brew "azure-cli"
brew "carapace"
brew "chezmoi"
brew "cmatrix"
brew "colima"
brew "libssh2"
brew "direnv"
brew "dnsmasq"
brew "docker"
brew "docker-buildx"
brew "docker-compose"
brew "docker-credential-helper"
brew "duckdb"
brew "ffmpeg"
brew "freetds"
brew "fd"
brew "fswatch"
brew "fzf"
brew "gawk"
brew "webp"
brew "gh"
brew "harfbuzz"
brew "pango"
brew "tesseract"
brew "git"
brew "gnu-sed"
brew "libevent"
brew "p11-kit"
brew "unbound"
brew "gnupg"
brew "hcloud"
brew "hugo"
brew "icu4c@76"
brew "icu4c@77"
brew "libheif"
brew "imagemagick"
brew "jq"
brew "openjdk"
brew "leiningen"
brew "libass"
brew "libffi"
brew "librsvg"
brew "node"
brew "mailsy"
brew "mas"
brew "md5sha1sum", link: true
brew "mise"
brew "mole"
brew "mosh"
brew "ncdu"
brew "neovim"
brew "nowplaying-cli"
brew "netcat"
brew "netpbm"
brew "nginx", restart_service: :changed
brew "nmap"
brew "node@20"
brew "ollama"
brew "openvino"
brew "pandoc"
brew "perl"
brew "pgcli"
brew "rtmpdump"
brew "pigz"
brew "pipx"
brew "pkgconf"
brew "podman"
brew "poppler"
brew "postgresql@14"
brew "pulumi"
brew "python@3.12"
brew "qemu"
brew "resvg"
brew "ripgrep"
brew "rsync"
brew "rtk"
brew "ruby"
brew "speedtest-cli"
brew "sevenzip"
brew "sshpass"
brew "starship"
brew "syncthing"
brew "tailscale"
brew "texlive"
brew "timewarrior"
brew "tldr"
brew "tmux"
brew "visidata"
brew "wget"
brew "yt-dlp"
brew "yazi"
brew "zoxide"
brew "zsh-autosuggestions"
brew "atlassian/acli/acli"
brew "databricks/tap/databricks"
brew "hashicorp/tap/terraform"
brew "jakehilborn/jakehilborn/displayplacer"
brew "FelixKratz/formulae/sketchybar"
brew "FelixKratz/formulae/borders"
brew "malpern/tap/sketchybar-toggle"
brew "switchaudio-osx"
brew "lawzava/scrape/scrape"
brew "shopify/shopify/themekit"
cask "1password"
cask "1password-cli"
cask "nikitabobko/tap/aerospace"
cask "anydesk"
cask "brainfm"
cask "chatgpt"
cask "font-monofur-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "sf-symbols"
cask "clickhouse"
cask "kindavim"
cask "kitty"
cask "loop"
cask "lm-studio"
cask "ngrok"
cask "obsidian"
cask "opencode-desktop"
cask "parallels"
cask "paste"
cask "rustdesk"
cask "shortcat"
cask "signal"
cask "speedify"
cask "tailscale-app"
mas "Affinity Designer", id: 824171161
mas "Affinity Photo", id: 824183456
mas "Amphetamine", id: 937984704
mas "BlueWallet", id: 1376878040
mas "Color Picker", id: 1545870783
mas "Dark Reader for Safari", id: 1438243180
mas "Final Cut Pro", id: 424389933
mas "LosslessCut", id: 1505323402
mas "Marked 2", id: 890031187
mas "Mate Translate", id: 1005088137
mas "PDF Expert", id: 1055273043
mas "Prompt", id: 1594420480
mas "Strongbox", id: 1481853033
mas "Telegram", id: 747648890
mas "The Unarchiver", id: 425424353
mas "WhatsApp", id: 310633997
go "golang.org/x/tools/gopls"
go "honnef.co/go/tools/cmd/staticcheck"
uv "aider-chat", with: ["pip"]
uv "graphifyy"
uv "specify-cli"
uv "xonsh[full]", with: ["xontrib-kitty"]
